# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
workflows:
  build_and_package:
    jobs:
      - godot_export

jobs:
  godot_export:
    docker:
      - image: barichello/godot-ci:latest
    steps:
      - checkout
      - run: godot --export "Windows Desktop" game-win64.exe
      - run: zip game-win64.zip game-win64.exe game-win64.pck
      - store_artifacts:
          path: game-win64.zip
          destination: windows-build.zip
      - persist_to_workspace:
          root: .
          paths:
            - game-win64.zip
